export const PLAYBACK_CONFIG = {
  HOLD_TO_2X_THRESHOLD: 500,
  CLICK_DETECTION_WINDOW: 300,
  OVERLAY_FADE_DURATION: 1000,
  SEEK_AMOUNT: 5,
  FAST_PLAYBACK_RATE: 2,
  LEFT_ZONE_RATIO: 1 / 3,
  RIGHT_ZONE_RATIO: 2 / 3,
} as const
